### ISSUE TITLE
How to run project step by step

### ISSUE THREAD

**Issue by oisonan1999** [erebus-attack/Bitcoin-Emulator#2]
Hello sir!
I have downloaded your project for the purpose of learning and learning. But I don't quite understand the steps in project. I also wonder about the file path data: Where did you get the data for starter_ips_fp, ip_reachability_fp, addr_msgs_fp, shadow_prefixes_fp, nonhidden_shadow_prefixes_fp, victim_as_path. Can you give me the source to get the data?.
Like you guys, can you show me step-by-step how to run which files first and which files later?
Thank you very much!

**Comment by akshayeshenoi** [comment]
Thanks for reaching out! The data is present in the 'Releases' tab here: https://github.com/erebus-attack/Bitcoin-Emulator/releases/tag/v0.1

After extracting it in the project root folder, you can proceed to run the code as described in the README: https://github.com/erebus-attack/Bitcoin-Emulator/tree/rap-publish#running-the-emulator

The example data used considers the Amazon AS as the victim node and the L3 AS as the attacker.

Once you run the simulation (it might take about 20 minutes), the results will be saved to the output/ directory. 

The code itself is documented thoroughly to give you an idea of the various inputs being used. You may prepare your own dataset to try out other attacker-victim scenarios. 

Hope this helps!
