### ISSUE TITLE
Code not working 

### ISSUE THREAD

**Issue by Mary333555** [erebus-attack/Bitcoin-Emulator#3]
- I changed the victim age to 1: victim_age =1

** Output **
>>> prepare_addr_broadcasts
Reading file.. ./data/addr-msgs.txt.gz
Killed

Kindly advise.

**Comment by akshayeshenoi** [comment]
Hi,

Changing the victim age to 1 should not affect the code. It seems to be working on my machine.
You may have run out of memory - a single run might consume as much as 4GB RAM. 

Hope this helps.
