### ISSUE TITLE
Error with prepare_hidden_shadow_ips

### ISSUE THREAD

**Issue by oisonan1999** [erebus-attack/Bitcoin-Emulator#7]
When I run the code I always get this bug
![image](https://user-images.githubusercontent.com/54930174/197323052-ea13e327-721e-44bb-a684-534013b6790c.png)
How can I fix this? Thank you

**Comment by oisonan1999** [comment]
This issue happen when I turn on the RAP

**Comment by akshayeshenoi** [comment]
Looks likes this is an error specific to windows (you can try googling it). 

We have tested our code only on Linux, so you may want to run it in a VM.

**Comment by oisonan1999** [comment]
I ran all the cases like in your article. But never once have I seen a failed attack. Whether RAP is enabled or not. Can you explain?. And I want to ask is there any way to improve RAP's logic algorithm?
