### ISSUE TITLE
The attack success print statement is always True

### ISSUE THREAD

**Issue by oisonan1999** [erebus-attack/Bitcoin-Emulator#8]
I ran all the cases like in your article. But never once have I seen a failed attack. Whether RAP is enabled or not. Can you explain?. And I want to ask is there any way to improve RAP's logic algorithm?

**Comment by akshayeshenoi** [comment]
We consider the attack to succeed if the attacker has occupied all outgoing connections before the end time of the simulation.

See https://github.com/erebus-attack/Bitcoin-Emulator/issues/4#issuecomment-1219359873.

**Comment by oisonan1999** [comment]
But I find that in many cases where the attacker can't take over the entire connection, the attack is still logged as successful, why is that?

**Comment by akshayeshenoi** [comment]
Please attach the simulation output so I can examine it.

**Comment by oisonan1999** [comment]
Here I tried giving 1 more log that is attack fails and the output is still successful.
[l3-amzn.txt](https://github.com/erebus-attack/Bitcoin-Emulator/files/9898643/l3-amzn.txt)

**Comment by akshayeshenoi** [comment]
Thank you for pointing out the behaviour. I have fixed the bug (#9) and merged into master.
